global:
  # How frequently to scrape targets by default.
  scrape_interval: 1s
  # How long until a scrape request times out.
  scrape_timeout: 500ms
  # How frequently to evaluate rules.
  evaluation_interval: 5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 1s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: "frontend"
    scrape_interval: 1s
    metrics_path: 'metrics'
    static_configs:
      - targets: ['edge-router']

  # The job name assigned to scraped metrics by default.
  - job_name: "catalogue"
    # How frequently to scrape targets from this job.
    scrape_interval: 1s
    # List of labeled statically configured targets for this job.
    static_configs:
      # The targets specified by the static config.
      - targets: ['catalogue']

  - job_name: "payment"
    scrape_interval: 1s
    static_configs:
      - targets: ['payment']

  - job_name: "user"
    scrape_interval: 1s
    static_configs:
      - targets: ['user']

  - job_name: "orders"
    scrape_interval: 1s
    # The HTTP resource path on which to fetch metrics from targets.
    metrics_path: 'metrics'
    static_configs:
      - targets: ['orders']

  - job_name: "cart"
    scrape_interval: 1s
    metrics_path: 'metrics'
    static_configs:
      - targets: ['carts']

  - job_name: "shipping"
    scrape_interval: 1s
    metrics_path: 'metrics'
    static_configs:
      - targets: ['shipping']

  - job_name: "queue-master"
    scrape_interval: 1s
    metrics_path: 'prometheus'
    static_configs:
      - targets: ['queue-master']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 1s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 1s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
